# Generated by Django 4.1.3 on 2023-07-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Data',
            new_name='Course',
        ),
    ]
